### PR TITLE
Redacted Read me file

### PR DESCRIPTION
**Pull request by IsaAnger**

### CODE REVIEW

**Review by dhruvabhat24 — COMMENTED** [review]
Can you please explain what exactly this Pr is about... 
When I checked the code I can see only one like added to the html code i.e title for the page and in readme a new line i.e Review code. Those are not needed . If you have done anything else please describe it below this comment

**Comment by IsaAnger** [comment]
Hello!  I am a student of a programming course.  I now have the discipline to learn GitHub.  My teacher gave me the task of finding an open source project and modifying it.  I chose your project as a training project.  I don't know what further tasks will be from my teacher, so maybe this is not the last action with your project.  I apologize for the inconvenience.

**Comment by dhruvabhat24** [comment]
I am happy to assist you with your tasks but for that you need to do a valid pr
 So do one thing clone the repo to your system run the html code and check if you can add some features or check for some bugs. Raise the issue first I will assign it to you and you can modify it and raise the pr. This may help you more.

**Comment by IsaAnger** [comment]
Okay, thank you

**Pull request closed without merging**
